### ISSUE TITLE
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by SludgePhD** [luxonis/depthai-gui#5]
Got this error after installing according to the readme instructions (on Linux):

```
> pip install depthai-gui
Defaulting to user installation because normal site-packages is not writeable
WARNING: Keyring is skipped due to an exception: g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)
Collecting depthai-gui
  Downloading depthai_gui-1.0.12-py3-none-any.whl (48.4 MB)
     |████████████████████████████████| 48.4 MB 10.8 MB/s            
Collecting depthai
  Downloading depthai-2.14.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 10.5 MB/s            
Collecting PySide2
  Downloading PySide2-5.13.2-5.13.2-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl (156.1 MB)
     |████████████████████████████████| 156.1 MB 200 kB/s             
Collecting opencv-python
  Downloading opencv_python-4.5.5.62-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.4 MB)
     |████████████████████████████████| 60.4 MB 10.7 MB/s            
Requirement already satisfied: docutils in /usr/lib/python3.10/site-packages (from depthai-gui) (0.16)
Collecting blinker
  Downloading blinker-1.4.tar.gz (111 kB)
     |████████████████████████████████| 111 kB 13.5 MB/s            
Collecting Qt.py
  Downloading Qt.py-1.3.6-py2.py3-none-any.whl (18 kB)
Collecting nine
  Downloading nine-1.1.0-py2.py3-none-any.whl (9.2 kB)
Requirement already satisfied: numpy>=1.17.3 in /usr/lib/python3.10/site-packages (from opencv-python->depthai-gui) (1.21.5)
Collecting shiboken2==5.13.2
  Downloading shiboken2-5.13.2-5.13.2-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl (832 kB)
     |████████████████████████████████| 832 kB 11.4 MB/s            
Using legacy 'setup.py install' for blinker, since package 'wheel' is not installed.
Installing collected packages: shiboken2, Qt.py, PySide2, opencv-python, nine, depthai, blinker, depthai-gui
    Running setup.py install for blinker ... done
Successfully installed PySide2-5.13.2 Qt.py-1.3.6 blinker-1.4 depthai-2.14.0.0 depthai-gui-1.0.12 nine-1.1.0 opencv-python-4.5.5.62 shiboken2-5.13.2
> depthai-gui 
Traceback (most recent call last):
  File "/home/sludge/.local/bin/depthai-gui", line 8, in <module>
    sys.exit(main())
  File "/home/sludge/.local/lib/python3.10/site-packages/PyFlow/Scripts/__init__.py", line 74, in main
    instance = PyFlow.instance(software="standalone")
  File "/home/sludge/.local/lib/python3.10/site-packages/PyFlow/App.py", line 575, in instance
    instance = PyFlow(parent)
  File "/home/sludge/.local/lib/python3.10/site-packages/PyFlow/App.py", line 108, in __init__
    self.canvasWidget = BlueprintCanvasWidget(self.graphManager.get(), self)
  File "/home/sludge/.local/lib/python3.10/site-packages/PyFlow/UI/Widgets/BlueprintCanvas.py", line 1764, in __init__
    self.canvas = BlueprintCanvas(graphManager, pyFlowInstance)
  File "/home/sludge/.local/lib/python3.10/site-packages/PyFlow/UI/Widgets/BlueprintCanvas.py", line 128, in __init__
    self.node_box.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.FramelessWindowHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
```

Perhaps a dependency version changed and should be pinned in `requirements.txt`?

**Comment by VanDavv** [comment]
Hi @SludgePhD, sorry for the issue.

We won't be updating the current depthai-gui and use [this experiment](https://github.com/luxonis/depthai-experiments/pull/273) as a starting point for the new and updated GUI demo.

**Comment by VanDavv** [comment]
Closing the issue due to the new GUI introduction, feel free to update and give it a try.
Thanks for reporting!
